### ISSUE TITLE
Tabelle article_slice Felder dürfen NULL sein

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/yconverter#13]
Die Felder value1-20, link1-10, linklist1-10 dürfen NULL sein sind sie aber nicht. Interessanterweise werden die Felder media1-10 und medialist1-10 umgestellt und dürfen NULL sein.

**Comment by tbaddade** [comment]
> Die Felder value1-20, link1-10, linklist1-10 dürfen NULL sein sind sie aber nicht.

Kann ich nicht nachvollziehen. In welcher Redaxo Version verwendest du den Converter? Wurde in der Instanz die Redaxo Updates nach und nach eingespielt?

Schau mal ob die Felder in der `rex_article_slice` Tabelle von R4 `NULL` sein dürfen.

**Comment by TobiasKrais** [comment]
Redaxo Version 4.6.2. In der R4 Datenbank dürfen die Felder bei mir nicht NULL sein.

**Comment by tbaddade** [comment]
> Redaxo Version 4.6.2. In der R4 Datenbank dürfen die Felder bei mir nicht NULL sein.

Sollten sie aber.
https://github.com/redaxo/redaxo4/blob/190d885b71c19eb8acbb6438adc90ff38abdb13a/redaxo/include/install/redaxo4_6.sql#L6

**Comment by TobiasKrais** [comment]
Interessant. Die Datenbank war ursprünglich eine ältere Redaxo Version die ich per Upgrade hochgezogen habe. Frag mich nicht, wie das zustande kommt, denn selbst in der 4.2er Redaxo Version darf das Feld NULL sein. Interessant ist, dass ich hier eine ganze Reihe Datenbanken von Redaxo Versionen habe, die bei diesen Feldern NOT NULL gesetzt haben!? Meinst du den patch kannst du trotzdem aufnehmen? Stören tut es ja nicht und bei den ganzen DBs von mir wäre das hilfreich.

**Comment by tbaddade** [comment]
Ich empfehle dir nur die Daten zu überspielen, so braucht das Addon nicht die komplette Tabellenstruktur von R5 zu berücksichtigen (falls R5 hier mal Anpassungen vornimmt) und auch die Feldtypen wären immer korrekt. Ansonsten müsste das Addon ggf. noch andere Daten/Strukturen anpassen.

Du könntest unten die DB-Verbindung zur R5 Instanz angeben und dann überspielen.

**Comment by TobiasKrais** [comment]
Ja, das ist das beste. Werde ich so machen.

**Comment by tbaddade** [comment]
Es wird empfohlen immer nur die reinen Daten zu überspielen. Info kommt auch in das AddOn.
