### ISSUE TITLE
Mindestbedingungen festlegen und abfragen

### ISSUE THREAD

**Issue by gharlan** [yakamara/yconverter#15]
Bei der Addoninstallation sollten die Mindestbedingungen abgefragt werden.

Aktuell benötigt es scheinbar PHP 5.4. Wollen wir das ändern, sodass es auf mehr Installation läuft? Also auf PHP 5.3?
Ab welcher Redaxo-Version funktioniert es? 
Nur mit UTF-8, oder?

**Comment by gharlan** [comment]
Aktuell läuft es scheinbar erst ab 4.6, da `rex_path` etc verwendet wird.

**Comment by tbaddade** [comment]
> Bei der Addoninstallation sollten die Mindestbedingungen abgefragt werden.

Finde ich gut. Hat in der Zwischenzeit @staabm bereits eingesetzt.

> Aktuell benötigt es scheinbar PHP 5.4. Wollen wir das ändern, sodass es auf mehr Installation läuft? 

Gern. Aber irgendwo müsste man den Schnitt machen. U.a. gebe ich sogar diese Info zu XForm aus
https://github.com/yakamara/yconverter/blob/master/pages/convert.inc.php#L28-L30

**Comment by tbaddade** [comment]
Ich schließe mal und sammeln die Infos weiter hier #21
