### ISSUE TITLE
xForm lang_textarea in textarea field_1, field_2, field_n umwandeln

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#17]
Memo aus Slack: Wenn eine `lang_textarea` auf YForm für R5 vorbereitet wird, sollte der Inhalt in verschiedene Felder gesplittet werden. Als Suffix dann `_clangid`.

(PR kommt keiner von mir, weil ich es selbst auch noch gar nicht benutzt habe - aber ich nehm das als Wunsch/Idee hier mal auf)

**Comment by Hirbod** [comment]
Zur Not hab ich auch lang_textarea jetzt auch hübsch nach R5 portiert. Wer's brauch, kann sich im Slack bei mir melden.
