### ISSUE TITLE
Installer?

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#23]
Ist das Addon mittlerweile, wenn auch mit Vorsicht zu genießen, bereit für den Installer? Werden die Änderungen an der aktiven Datenbank vorgenommen oder könnte man nicht auch dafür eine Zieldatenbank angeben?

**Comment by tbaddade** [comment]
> Ist das Addon mittlerweile, wenn auch mit Vorsicht zu genießen, bereit für den Installer? 

man kann es sicherlich n den Installer legen, wobei wir aber die REDAXO-Mindestversion noch herabsetzen wollten. Ist nur grad zeitlich alles recht problematisch.

> Werden die Änderungen an der aktiven Datenbank vorgenommen 

Ja, aber nicht an den Tabellen selbst. Die relevanten Tabellen werden in derselben Datenbank kopiert und modifiziert. Bsp. `rex_article` wird zu `yconverter_rex_article`

> oder könnte man nicht auch dafür eine Zieldatenbank angeben?

Man kann im Addon die reinen Tabellendaten in eine Zielinstanz transferieren.

**Comment by alexplusde** [comment]
Danke @tbaddade. Ich werde das Addon nächste Woche mal einsetzen und versuche, mich bei Gelegenheit mit einem Addon-Readme-Text zu revanchieren, damit solche Fragen direkt beantwortet werden.

**Comment by alexplusde** [comment]
Wir haben es eingesetzt, gesehen, dass da ja im Addon schon viel erklärt wird. Den Text könnte man hier mal in die ReadMe auf Github packen.

**Comment by alexplusde** [comment]
#27 so ist nach außen mal klarer, was das Addon macht, bevor man es installiert. Hätte es immer noch gern im Installer ;)

**Comment by alexplusde** [comment]
Ein Jahr später nochmals die Frage: Spricht etwas dagegen, das Addon in den Installer aufzunehmen?

**Comment by tbaddade** [comment]
> Spricht etwas dagegen, das Addon in den Installer aufzunehmen?

Ein Jahr später definitiv. Ich müsste sehen inwiefern der Converter mit der aktuellen Rex 5.6.2 Version kompatibel ist.

**Comment by alexplusde** [comment]
@tbaddade Prinzipiell kompatibel, bis auf einen evtl. Fehler mit den Meta-Infos, das ich gerade bei Slack geschrieben habe.

Falls es doch mehr ist, sage ich Bescheid - das hindert einen ja wiederum nicht daran, ein Update rauszubringen ;)

**Comment by shaack** [comment]
Habe es grade mit Redaxo 5.6.4 genutzt und es hat einwandfrei funktioniert. 4.7.2 => 5.6.4

**Comment by alexplusde** [comment]
Ist zu 5.6.4 gut kompatibel. Bitte in den Installer!

**Comment by alexplusde** [comment]
Kommt schon! ;)

Es kann auch gleich in die aktuelle 4.7.3 mit rein.
