### ISSUE TITLE
Fehler 500 beim Aufruf der YConverter-Seite im Backend

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#26]
REDAXO: 4.6.2
PHP: 5.6.32
MySQL: 10.1.28
(Cloudflare-Hosting)

**Comment by alexplusde** [comment]
Außerdem (in einem anderen Paket, vlt. damit zusammenhängend):
```
Parse error: syntax error, unexpected '{', expecting ']' in /kunden/www/redaxo/include/addons/yconverter/lib/YConverter/Converter.php on line 210
```

**Comment by isospin** [comment]
bekomme auch einen 500er...

REDAXO: 4.5.1
PHP: 5.6.30
MySQL: 5.6.19
Domainfactory

Der Fix von Tobias behebt dieses Problem nicht

**Comment by alexplusde** [comment]
der fix wurde auch noch nicht gemerged... 
@isospin den Fehler (und den von mir korrigierten Code) findest du hier: https://github.com/yakamara/yconverter/pull/25#pullrequestreview-74422328

**Comment by isospin** [comment]
@alexplusde mhh... ja, sorry, damit gehts: https://github.com/TobiasKrais/yconverter/commit/088d541da70803e50d4c783f65d8fa3ee9b1fa2c
copy&paste fehler bei mir... .-)

**Comment by isospin** [comment]
upps, muss leider zurückrudern... geht nicht bei mir (hatte den fix auf dem falschen server eingebaut)

**Comment by tbaddade** [comment]
@isospin Was genau funktioniert nicht mit dem Fix?

**Comment by isospin** [comment]
beim aufruf des addons gibt es trotz fix immer noch einen 'HTTP ERROR 500'

**Comment by tbaddade** [comment]
Was sagen die Logfiles zum 500er?

**Comment by skerbis** [comment]
Bei mir kommt aktuell noch folgendes dazu: 

`AH01071: Got error 'PHP message: PHP Parse error: syntax error, unexpected ')', expecting ']' in /var/…/addons/yconverter/lib/YConverter/Converter.php on line 210\n', referer: https://domain.de/redaxo/index.php?page=addon&info=AddOn%20%22yconverter%22%20wurde%20aktiviert`

**Comment by skerbis** [comment]
https://redaxo.org/forum/viewtopic.php?f=26&t=21962&p=122643#p122643

**Comment by tbaddade** [comment]
Der Fix ist nun in der aktuelle GH Version enthalten. Könnte grad jemand das AddOn im Backend aufrufen und den Fix bestätigen. Habe hier lokal grad keine R4 Version am Start.

**Comment by skerbis** [comment]
@tbaddade jupp ist wieder gut. Gerade getestet.
