### ISSUE TITLE
new article -> new rex_article_content

### ISSUE THREAD

**Issue by skerbis** [yakamara/yconverter#30]
könnte ggf. auch zu einer Vereinfachung helfen.

**Comment by tbaddade** [comment]
`new article` ist seit der Version 3.3 deprecated und wurde nur in der compat mitgenommen.

https://github.com/redaxo/redaxo4/blob/master/redaxo/include/classes/class.compat.inc.php#L151-L153

**Comment by skerbis** [comment]
Ok. Habe ich wohl über die Jahre mitgeschleppt und ist so nicht aufgefallen.
