### ISSUE TITLE
DB-Typ MyISAM vs. InnoDB

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#32]
In R5 werden Tabellen als InnoDB angelegt, aus dem Converter kommen sie als MyISAM.

**Comment by tbaddade** [comment]
Deshalb zur Zeit am besten nur die Daten übertragen.

**Comment by alexplusde** [comment]
Das schlug bei mir leider auch fehl :(

**Comment by alexplusde** [comment]
Außerdem muss auch auf das richtige UTF8-Format geachtet werden (utf8mb4)
