### ISSUE TITLE
rex_file vs. rex_media

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#33]
yconverter sollte beim konvertieren `rex_file` in `yconverter_rex_media` umbennenen, statt in `yconverter_rex_file`

**Comment by tbaddade** [comment]
Das sollte so sein siehe https://github.com/yakamara/yconverter/blob/master/lib/YConverter/Converter.php#L376

**Comment by alexplusde** [comment]
also bei mir wurde trotzdem eine yconverter_rex_file-Tabelle mit angelegt.

**Comment by alexplusde** [comment]
habe jetzt mal erfolgreich eine Datenbank über den regulären Weg übertragen: da wird bspw. yconverter_rex_file 2x importiert: als rex_file (neue Tabelle) und als rex_media (Daten importiert). Dasselbe passiert auch mit der Cronjob-Tabelle, mit YCom-Tabellen, etc.

**Comment by tbaddade** [comment]
> yconverter sollte beim konvertieren rex_file in yconverter_rex_media umbennenen, statt in yconverter_rex_file

Ich habe mehrfach eine Demo konvertiert. Bei mir wurde immer die `yconverter_rex_media` angelegt. Kann das nicht reproduzieren. 

Gern wieder öffnen wenn du neue Kenntnisse hast.

**Comment by alexplusde** [comment]
Viele der Issues, die du gerade ansprichst, sind vom 3. Februar. Evtl. war ich hier nicht sicher im Umgang mit den Addon und habe es verkehrt eingesetzt, oder eine alte Version gehabt. Ich melde mich, falls es mir nochmals passiert.
