### ISSUE TITLE
Weitere Ersetzungen hinzufügen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#34]
* textile-Funktion in `$textile = markitup::parseOutput ('textile', "REX_VALUE[5]");`
* `OOMedia::getMediaByFilename();` in `rex_media::get();`

**Comment by tbaddade** [comment]
> OOMedia::getMediaByFilename(); in rex_media::get();

Der Part sollte bereits ersetzt werden, siehe https://github.com/yakamara/yconverter/blob/57e6a4f8e203e13f7c7a6484b1b192411e3a5e4c/lib/YConverter/Converter.php#L95

**Comment by tbaddade** [comment]
Wenn du neue Kenntnisse hast, gern hier reinschreiben. Bitte dabei nur beachten, das eigene ausgelagerte Dateien unberührt bleiben

**Comment by alexplusde** [comment]
Einverstanden. 

Zum Issue bez. Textile? Das gibt's ja nicht mehr built-in, wenn ich das richtig sehe, sondern nur in Form des Markitup-Addons. Konvertieren möglich? Manuell darauf hinweisen?

**Comment by tyrant88** [comment]
Bei mir war noch ein `OOCategory::getChildrenById(273,true);` drin.
Das würde dann zu `rex_category::get(273)->getChildren(true);`
