### ISSUE TITLE
fehlende option "auto increment" in rex_media

### ISSUE THREAD

**Issue by tyrant88** [yakamara/yconverter#35]
In der konvertierten yconverter_rex_media tabelle ist die Spalte "id" kein Auto-Inkrement Feld.
Das führt dazu, dass man beim Hinzufügen neuer Dateien in Medienpool Fehlermeldungen bekommt.

**Comment by tbaddade** [comment]
siehe https://github.com/yakamara/yconverter/issues/8

Hintergrund ist, dass das AddOn in der Zwischenzeit vom Core neu hinzugefügte Spalten nicht berücksichtigen kann.

**Comment by tyrant88** [comment]
Ich bin nach der Anleitung im AddOn vorgegangen. Die Übertragung mit dem Formular ging nicht, also über den adminer. Das produziert dieses Issue.
Da kannst du das doch nicht einfach "closen"?!

**Comment by tbaddade** [comment]
Es wird empfohlen nur die Daten und nicht die Struktur zu übertragen. Die Struktur kann zu diesem Zeitpunkt nicht mit der vom Core mehr übereinstimmen. Das Problem besteht so auch, wenn du nur die Daten überträgst?

**Comment by tyrant88** [comment]
Hab ich da einen alten Text? Bei mir wurde da nichts empfolen.
Ich nehme mal an das die rex_media Tabelle ein auto inkrement hat, also würde das Problem nicht auftauchen.
Ich bin jetzt nicht drin in der Materie, aber ich dachte du erzeugst doch die yconverter_rex_media Tabelle, kann man da nicht das auto_increment setzen?

**Comment by tbaddade** [comment]
> Ich bin jetzt nicht drin in der Materie, aber ich dachte du erzeugst doch die yconverter_rex_media Tabelle

Korrekt, d.h. aber nicht dass die Struktur der konvertierten Tabelle mit der Struktur der aktuellsten REDAXO Version übereinstimmt.

**Comment by tyrant88** [comment]
wir reden hier von der Spalte "id"....

**Comment by alexplusde** [comment]
Das Problem kann ich aktuell nicht mehr bestätigen.

**Comment by tbaddade** [comment]
fixed in 367f36c1cd68f53453d2b6009fd43c5f33753be1
