### ISSUE TITLE
new article wird nicht umbenannt

### ISSUE THREAD

**Issue by skerbis** [yakamara/yconverter#38]

**Comment by tbaddade** [comment]
> new article wird nicht umbenannt

das ist aber auch schon ziemlich veraltet.
https://github.com/redaxo/redaxo4/blob/master/redaxo/include/classes/class.compat.inc.php#L151-L152

**Comment by skerbis** [comment]
Da siehst du, wie alt meine Seiten sind. Die Seite ist ursprünglich aus 2007

**Comment by skerbis** [comment]
Vielleicht reicht aber auch eine Warnung beim Konvertieren? Wei bei den $REX globals
