### ISSUE TITLE
Database conversion

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/yconverter#4]
Hi Thomas,

die Addon-Idee von dir ist super! Da will ich gerne helfen. Wenn ich deinen Code anschaue brauchst du noch ein SQL Skript zum konvertieren der Datenbank. Here it is:
https://www.dropbox.com/s/e5k0ccd01sqa3ra/update4_7_to_5_2.sql?dl=0

Liebe Grüße,

Tobi

**Comment by alexplusde** [comment]
Einen Redaxo-Taler an @TobiasKrais! Bist du auch bei Slack?

**Comment by TobiasKrais** [comment]
Hi. Danke. Jetzt bin ich auch bei Slack.

Wäre es nicht sinnvoll, das Addon in den Installer zu übernehmen?

**Comment by tbaddade** [comment]
@TobiasKrais Danke dir für das Skript. Die Änderungen der Datenbank passieren bereits und werden ab [hier notiert](https://github.com/yakamara/yconverter/blob/master/lib/YConverter/Converter.php#L190).

**Comment by tbaddade** [comment]
@TobiasKrais Ich hatte gestern mir nochmals dein Skript genauer angesehen. Bei dir gehen die Daten von slice.php und slice.html verloren.

**Comment by TobiasKrais** [comment]
Hi Thomas, ja das war Absicht. Ich nutze die beiden Felder in keinem Projekt. value20 ist bei mir für einen anderen Wert vorbelegt. Danke fürs genaue drüber schauen. Der yconverter ist echt cool! Super Arbeit!

**Comment by tbaddade** [comment]
> value20 ist bei mir für einen anderen Wert vorbelegt

Nur zur Info: Die Inhalte werden in den values angehangen. Es sollte daher nichts gelöscht werden.  Man kann auch ganz oben in der Class die value Spalten für php und html selbst bestimmen.
