### ISSUE TITLE
Kategorie-Metainfos-Konvertierung überprüfen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#41]
Wenn man cat-Metainfos verwendet, werden diese zwar in der rex_article-Tabelle übertragen, jedoch scheint es zu Problemen bei der metainfo-Feld-Tabelle zu kommen. Ein Metainfo-Feld lässt sich dann nicht mehr erstellen, weil es ja bereits in der rex_article-Datenbanktabelle ist.

**Comment by tbaddade** [comment]
Verstehe nicht ganz warum du diese anlegen musst. Die werden m.E. mit übertragen. 

siehe https://github.com/yakamara/yconverter/blob/master/lib/YConverter/Converter.php#L226-L240

**Comment by alexplusde** [comment]
ja, hat mich auch verwundert. Ich behalte es mal im Auge beim nächsten Einsatz.

**Comment by alexplusde** [comment]
Ich habe nicht den vorgeschlagenen Übertragungsweg verwendet, sondern manuell über Adminer ex/importiert.

**Comment by tbaddade** [comment]
Warum fehlte aber das Feld in der MetaInfo-Tabelle?

**Comment by alexplusde** [comment]
Evtl deswegen: https://github.com/yakamara/yconverter/issues/44#issuecomment-436742503

**Comment by tbaddade** [comment]
Das Feld konnte in der MetaInfo-Tabelle der R5 Instanz nicht angelegt werden, wenn die Tabellenstruktur mit übertragen wurde. Aber das Feld existierte ja bereits in der R4 Instanz, da es als Column in der rex_article vorhanden ist. Das Fehler des Feldes in der MetaInfo-Tabelle der R4 Instanz ist kurios.

Ich schließe mal. Wenn es wieder auftritt, gern öffnen und einen nachvollziehbaren Weg bitte skizzieren.
