### ISSUE TITLE
XForm zu YForm: mass_edit-Feld fehlt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#42]
Mit Adminer importierte YForm-Tabellen erzeugen Fehler in der Table Manager-Übersicht, da bspw. das mass_edit-Feld fehlt. Ein Reinstallieren von YForm und dem Table Manager fixen das Problem - soweit wir das beurteilen konnten - selbständig.

/cc @skerbis für deine Anleitung

**Comment by tbaddade** [comment]
Kannst du dazu einen PR erstellen?

**Comment by alexplusde** [comment]
Leider nicht im Moment, ich sammel da erst mal noch Erfahrungen.
