### ISSUE TITLE
Language code nicht gesetzt unter System/Sprachen

### ISSUE THREAD

**Issue by shaack** [yakamara/yconverter#43]
Nach der Konvertierung mit yConverter (4.7.2 nach 5.6.4) wurden zwar die Sprachen unter System/Sprachen angelegt, aber das Feld "Code" ist bei beiden Sprachen leer im R5.

**Comment by tbaddade** [comment]
Ich meine, das Feld gibt es so nicht in Rex4.

**Comment by shaack** [comment]
Verstehe. War trotzdem ne blöde Fälle. Wahrscheinlich wäre eine zusätzliche Dokumentation sinnvoll, die erklärt, was man zusätzlich manuell durchführen und prüfen muss.

**Comment by tbaddade** [comment]
> Wahrscheinlich wäre eine zusätzliche Dokumentation sinnvoll, die erklärt, was man zusätzlich manuell durchführen und prüfen muss.

Sehr gern. Magst du das übernehmen @shaack ?

**Comment by shaack** [comment]
Ich kann es anfangen. Kann das alles in die README?

**Comment by alexplusde** [comment]
Da gibts ein Sammelissue in den Tricks bei FOR Von @skerbis

**Comment by skerbis** [comment]
Es gibt jetzt auch eine Doku die gerne ergänzt werden kann

**Comment by shaack** [comment]
"Findet YConverter Stellen im konvertierten Quellcode, die später nachgearbeitet werden müssen zeigt YConverter diese im Protokoll an.". Wäre das nicht genau so ne Stelle? Dann erweitere ich jetzt erst mal das Protokoll, ok?

**Comment by tbaddade** [comment]
> "Findet YConverter Stellen im konvertierten Quellcode, die später nachgearbeitet werden müssen zeigt YConverter diese im Protokoll an."

Kannst du für diesen Text gleich eine bessere Formulierung bilden @shaack ?
