### ISSUE TITLE
YCom - Passwörter konvertieren

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#49]
Wenn diese bereits in sha1 vorliegen am Beispiel von Passwort `test123`

`<?= rex_login::passwordHash("07b074b64dcdbcd037bed158228dfa36dcf462ba", true); ?>` (getestet)

`<?= rex_login::passwordHash("test123", false); ?>` (ungetestet)

**Comment by tbaddade** [comment]
Wie kann man einen prehash Wert von einem unverschlüsselten Passwort unterscheiden?

**Comment by alexplusde** [comment]
Laut https://stackoverflow.com/questions/2982059/testing-if-string-is-sha1-in-php

```
function is_sha1($str) {
    return (bool) preg_match('/^[0-9a-f]{40}$/i', $str);
}
```

Es wird in den allerallerallerallerallerallerallerallerwenigsten Fällen jemand zufällig als Klartext-Passwort ein `40 characters hexadecimal string` verwenden.

**Comment by staabm** [comment]
Wenn man mit passwort-hash arbeitet, kann man dort die user automatisch auf ein anderes hashing verfahren upgraden. Das macht man in der regel beim login.

Machen wir im backend auch

Siehe auch http://php.net/manual/en/function.password-needs-rehash.php

**Comment by alexplusde** [comment]
Hieße das, man könne die YCom-Hashs 1:1 übernehmen, da YCom auf der rex_login-Klasse basiert? (Ich meine, dass das aktuell nicht geht)

**Comment by staabm** [comment]
> Hieße das, man könne die YCom-Hashs 1:1 übernehmen, da YCom auf der rex_login-Klasse basiert? (Ich meine, dass das aktuell nicht geht)

Ich hab keine ahnung wie es aktuell funktioniert. Ich habe nur einen weg gezeigt wie man normalerweise geschickt mit diesem problem umgehen kann

**Comment by alexplusde** [comment]
@tbaddade Schwierig, da mein Code ja auf der rex_login-Klasse für R5 basiert und YConverter im R4-Kontext ausgeführt wird. Eine Alternative wäre vielleicht, Das in R5 YCom zur Verfügung zu stellen und es bei YConverter bei einem Hinweis zu belassen? Schließlich wird das R4 Community Addon im Moment sowieso nicht 1:1 für YCom aufbereitet.

@staabm finde es bei deinem Vorschlag kritisch, dass Hashs nicht geupdatet werden, ohne dass sich die Person einloggt. Das könnte dazu führen, dass unsichere Hashs in der Datenbank verweilen.

**Comment by staabm** [comment]
> @staabm finde es bei deinem Vorschlag kritisch, dass Hashs nicht geupdatet werden, ohne dass sich die Person einloggt. Das könnte dazu führen, dass unsichere Hashs in der Datenbank verweilen.

Da man die klartext-passwörter in der regel nicht kennt, gibt es eigentlich keine Alternativen

**Comment by alexplusde** [comment]
Es ist getestet. Siehe Beispiel zu Beginn des Issues. Ich übergebe einen Hash aus dem `R4 community`-Addon und erhalte einen neuen Hash zurück, mit dem ich mich via YCom einloggen kann, wenn ich diesen in die Datenbank zum passenden Benutzer schreibe.

**Comment by alexplusde** [comment]
Hier wird nachgesehen, ob das übergebene Passwort prehashed wurde oder nicht: 
https://github.com/redaxo/redaxo/blob/dd8abf6769ce9aac3f4387649aec79912dee7538/redaxo/src/core/lib/login/login.php#L475

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/tricks/pull/181
