### ISSUE TITLE
Slides in Arbeitsversion in falscher Reihenfolge

### ISSUE THREAD

**Issue by omphteliba** [yakamara/yconverter#5]
Das Ausgangssystem läuft unter Redaxo v. 4.6.2 mit dem Version Addon v 0.2

Die Slides der Liverversionen sind in der richtigen Reihenfolge. Aber die Arbeitsversionen sind durcheinander.

Ich habe mir die entstandene yconverter_rex_article_slice Tabelle angeschaut und wenn ich nach revision und dann priority sortiere sehe ich, daß die priority für die Live Artikel von 1 bis 17 ansteigt. Danach kommen die Werte für die Arbeitsversions-Slices nicht mehr aufsteigend:

```
priority
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17 <- letzte Live-Slice
0 <- erster Arbeits-Slice
6
10
14
19
105
124
4723
6567
7320
7366
8158
8159
8160
8161
8162
10170
```

**Comment by tbaddade** [comment]
fixed via https://github.com/yakamara/yconverter/commit/e2991ca32d3c8caf80220c1dd3694543f3cb5c0d
