### ISSUE TITLE
rex_article_slice ließen sich nicht kopieren: a356_is_online fehlt

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#50]
`Fehler in der SQL-Abfrage (1054): Unknown column 'a356_is_online' in 'field list'`

**Comment by tbaddade** [comment]
Woher kommt das Prefix `356_` ?

**Comment by alexplusde** [comment]
Wird ein Addon sein, oder? Eins für Blöcke online/offline schalten.

**Comment by pschuchmann** [comment]
Das müsste das Addon slice_onoff, bzw dessen Nachfolger slice_status sein. Wenn der Feldname auf status geändert wird, funktioniert auch direkt das bloecks Addon.

**Comment by tbaddade** [comment]
Dritt AddOns können nur begrenzt unterstützt werden.

**Comment by alexplusde** [comment]
Moment. Das heißt aber nicht, dass ycom die Übertragung der Tabelle komplett verweigern darf!

**Comment by tbaddade** [comment]
> Ohne Fehlermeldung.

Das hattest du geschrieben. Ist für mich eine klare Fehlermeldung

> Fehler in der SQL-Abfrage (1054): Unknown column 'a356_is_online' in 'field list'

**Comment by alexplusde** [comment]
Das ist, wenn ich die db manuell importiere. Ansonsten läuft die Übertragung in yconverter ohne sichtbare Fehlermeldung. Alle anderen Tabellen werden übertragen. Vielleicht war ich da nicht deutlich genug.
