### ISSUE TITLE
Fehlen 2 Dateien?

### ISSUE THREAD

**Issue by kochundsimon** [yakamara/yconverter#52]
Bei der Installation des Addons in Redaxo 4.6. fehlen die beiden Dateien:
config.inc.php
install.inc.php
Vergessen, hier mit einzupacken?

**Comment by kochundsimon** [comment]
Ok, die fehlen wohl nicht, sondern wurden bei dieser Version entfernt. Aber wie bekomme ich das dann installiert? Ohne die beiden Dateien, installiert er zwar, aktivieren geht schon nicht mehr. Tipp?

**Comment by alexplusde** [comment]
wurden die vielleicht nicht erfolgreich hochgeladen?

**Comment by alexplusde** [comment]
Ah, sorry, du warst in der "falschen" Branch. Es gibt YConverter jetzt auch für R5.

Hier wolltest du hin: https://github.com/yakamara/yconverter/tree/redaxo4
