### ISSUE TITLE
Titel des Addons ändern, Branch erwähnen

### ISSUE THREAD

**Issue by alexplusde** [yakamara/yconverter#53]
siehe #52 
![image](https://user-images.githubusercontent.com/3855487/54491606-0c5f3e80-48c0-11e9-96ec-8d89509a3679.png)

Hier müsste jetzt stehen: REDAXO5-Addon, das REDAXO4-Daten importiert.

Und in der README.md sollte aktualisiert werden - das Vorgehen bezieht sich ja noch auf R4.

**Comment by AWqxKAWERbXo** [comment]
wurde erledigt
