### ISSUE TITLE
Danke

### ISSUE THREAD

**Issue by skerbis** [yakamara/yconverter#6]
Das Addon tut genau was es soll. 
Klar, es ist viel Nacharbeit erforderlich, aber durch die aussagekräftigen Fehlermeldungen in REX5 kein Thema und keine Sucherei. Danke.

**Comment by alexplusde** [comment]
Da bekommt man ja richtig Lust, das zu testen :)

**Comment by skerbis** [comment]
Bedeutet aber nicht, dass es jeder benutzen kann. Man sollte schon wissen was zu tun ist. Ist definitiv nichts für den Installer.

**Comment by tbaddade** [comment]
> Ist definitiv nichts für den Installer.

Sehe ich ein wenig anders. Den Installer sollten nur Admins bedienen und damit auch wissen was sie sich in die Instanz holen und installieren.

PS: Danke für die Blumen :)

**Comment by gharlan** [comment]
Stimme da @tbaddade zu, das Addon sollte schon irgendwann in den Installer.

**Comment by gharlan** [comment]
Das Issue hier kann aber eigentlich zu, oder?
