### ISSUE TITLE
Testing :: Version REX5 :: REDAXO 4.5 zu 5.8.1

### ISSUE THREAD

**Issue by skerbis** [yakamara/yconverter#62]
Beim Versuch die DB von REDAXO 4.5 einzulesen: 

` Error while sending QUERY packet. PID=27673 in redaxo/src/core/lib/sql/sql.php on line 296`

```log
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 341
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 350
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 438
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 308
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 311
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 93
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 102
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 102
Warning: Cannot modify header information - headers already sent by (output started at /var/www/vhosts/irgendeineDomain.de/rex5.irgendeineDomain.de/redaxo/src/core/lib/error_handler.php:262) in redaxo/src/core/lib/response.php on line 102
```

```��[koG���_����t���p,Yov���3�@�h���E $e�^��sn7)RJ��Y6 B�Qu��[U�~���b��|����{��k~�x~q��h��||��>Κ���r=*&�����қ�t�O���ISɏ���g�ٸ�V�q��X����C�^T���|����׳u׼�y��Z��jg��]7�������k�V��]SЫ�Ѻ��>��V���{��~.��⿷�w9^^�� �����t���މ��ɇ���z>�&�n�|U��Ns������m���Y����坁���U7���8�O�����j=;�\ X�*&�l���j:[6��l`������m3�hсV�c���B\�O/��|�-&���ڧ>�� ��է��Tc�b|�^f��V/^`�0�I���8}��ΨK@�-.��c���|<6���Թ��S��6n�G�^ϫ�v�~4��y7�7���S���۷cs�s�������YV��tv����ۜ�85�ߧ4�^��/g��a	�@��j�,g���1ǫ5�\�/����k��d�j�����9�����Ks�]s�m=0���,��>��ys8(����fY>tf������->�T� MBᵩ�߹��9_��-�o�I���R=;-�JX�z���Y��U��񤯯�n.���=x�7���!7f]��8??y��@��]P���`���!�}N���m�i�^޵��j�ܮ������q����Ň��V��e7��-���&Cl��~,����߿z��m9����b1���lg�{�]�F5��b9z@nX%7",I;*��t6����k�\�Ϳ�����w?���?�S��k�?��ӟ꺆 H���q��^]+�AS��i�u�5�v8�}�`Ze�p��e�ٗ���GR��͠��$W��T�9��3���Z�����Y�A�Ag��M.��O�3�N�	lЩ�=�џ��6	c	t��v��.�����ڳK�q0K5�u�9� e�m>5��M� ���!```

**Comment by AWqxKAWERbXo** [comment]
ich glaube, du musst ein R5.3 als Zielinstallation verwenden und anschließend erst den core durchupdaten.

**Comment by tbaddade** [comment]
> du musst ein R5.3 als Zielinstallation verwenden und anschließend erst den core durchupdaten.

Wie kommst du darauf @alexplusde

**Comment by AWqxKAWERbXo** [comment]
Bei mir gab es bei höheren Versionen von R5 auch Probleme mit dem konvertieren.

**Comment by skerbis** [comment]
Zur Info es geht um den Master in diesem Repo, in REDAXO 5.8.1. Ich glaube in diesem Fall ist das Problem der index von rexsearch in 4.5. Ich teste noch mal und werde berichten

**Comment by AWqxKAWERbXo** [comment]
den index kannst / solltest du vorher entfernen. der ist oft einfach zu groß. und wird nicht benötigt.

**Comment by skerbis** [comment]
Man kann ihn vorab nicht abwählen. Es wird jede Tabelle mit rex_ gezogen

**Comment by AWqxKAWERbXo** [comment]
Dann leere sie doch und erstelle hinterher den Index neu, falls die 4.x noch im Einsatz bleiben muss...

**Comment by skerbis** [comment]
Ok ... ich bin hier nun ein Stück weiter ... jetzt hänge ich bei Fehlende Tabellen und Spalten überprüfen. Diese werden anscheinend geprüft, aber nicht übernommen? 

> Folgende Felder sind der REDAXO 5 Tabelle rex_article nicht bekannt
Heißt das ich muss diese selbst anlegen? 

Denn versuche ich nach der Überprüfung die Daten zu übertragen ... whoopst es wieder ... 

>SQLSTATE[21S01]: Insert value list does not match column list: 1136 Column count doesn't match value count at row 1

Kann jetzt leider nicht mehr weiter testen. Habe das Projekt jetzt mit der 4er Version konvertiert.
