### ISSUE TITLE
Weitere Ersetzungen

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/yconverter#7]
In Modulen und Templates könnte noch folgender Strings ersetzt werden:
'rex_img_type' => 'rex_media_type',
'rex_img_file' => 'rex_media_file'

Beispiel neuer img tag:
`<img src="index.php?rex_media_type=meinType&rex_media_file=meinBild.jpg" alt="">`

Außerdem für YForm Module kann folgende Ersatzung automatisiert vorgenommen werden:
'db2email' =>'tpl2email'

**Comment by tbaddade** [comment]
close via #9
