### ISSUE TITLE
rex_media hat keinen Autoincrement und falschen Default '0'

### ISSUE THREAD

**Issue by TobiasKrais** [yakamara/yconverter#8]
Nach dem Durchlauf von yconverter fehlt der Tabelle rex_media der AUTO_INCREMENT Wert. Es kann nur ein Medium in den Medienpool hinzugefügt werden. Dieser hat den ID-Wert '0'. Beim hinzufügen des zweiten Mediums kommt der Insert Fehler. Lösungs-SQL:
`ALTER TABLE `rex_media` CHANGE `id` `id` INT(11) NOT NULL AUTO_INCREMENT;`

**Comment by TobiasKrais** [comment]
Ursache liegt in der Umbenennung des primary keys der Tabelle: https://github.com/yakamara/yconverter/blob/master/lib/YConverter/Converter.php#L349

**Comment by tbaddade** [comment]
Das müsste dann noch bei weitere Tabellen passieren. Überall dort, wo ein Feld in das Feld `id`umgewandelt wird.

Du übernimmst die Tabellen direkt in die R5 Instanz? Ich übertrage bisher nur die reinen Daten aus den konvertieren Tabellen in die R5 Instanz. Daher ist das bisher nicht aufgefallen.

**Comment by TobiasKrais** [comment]
Ja, das ist eine gute Idee nur den Inhalt zu übertragen. Warum bin ich da nicht drauf gekommen!?
Es sind noch zwei Tabellen betroffen:
ALTER TABLE rex_clang CHANGE id id INT(11) NOT NULL AUTO_INCREMENT;
ALTER TABLE rex_metainfo_field CHANGE id id INT(11) NOT NULL AUTO_INCREMENT;

**Comment by tbaddade** [comment]
Es wird empfohlen immer nur die reinen Daten zu überspielen. Info kommt auch in das AddOn.
